version: '0.2'
language: en
ignorePaths:
  - node_modules/**
  - .vscode/**
  - .git/**
  - .gitignore
  - migrations/**
  - package.json
  - .prettierrc
words:
  - badbunnypr
  - billieeilish
  - bursty
  - dualipa
  - Eilish
  - hostnames
  - issettingsopen
  - jvane
  - Lipa
  - neonctl
  - neondatabase
  - PIKOTARO
  - pooler
  - Postg
  - ppap
  - repost
  - reposted
  - Rossi
  - selenagomez
  - sslmode
  - Synthetix
  - taylorswift
  - topbar
  - vitest
