version: '0.2'
language: en
ignorePaths:
  - node_modules/**
  - .vscode/**
  - .git/**
  - .gitignore
  - migrations/**
  - package.json
  - .prettierrc
words:
  - badbunnypr
  - billieeilish
  - bursty
  - dualipa
  - Eilish
  - hostnames
  - IEND
  - IHDR
  - issettingsopen
  - jvane
  - Lipa
  - neonctl
  - neondatabase
  - nosniff
  - PIKOTARO
  - pooler
  - Postg
  - ppap
  - repost
  - reposted
  - Rossi
  - selenagomez
  - sslmode
  - sveltekit
  - Synthetix
  - taylorswift
  - topbar
  - unstub
  - vitest
  - NXDOMAIN
  - addrs
  - ilike
  - Unfollowing
  - heis
  - hevx
  - heim
  - heix
  - ftyp
