version: '0.2'
language: en
ignorePaths:
  - node_modules/**
  - .vscode/**
  - .git/**
  - .gitignore
  - migrations/**
  - package.json
  - .prettierrc
words:
  - bursty
  - hostnames
  - neonctl
  - neondatabase
  - pooler
  - Postg
  - vitest
